SECTOR_STOCKS = {
    "Banking": [
        {"symbol": "HDFCBANK.NS", "name": "HDFC Bank"},
        {"symbol": "ICICIBANK.NS", "name": "ICICI Bank"},
        {"symbol": "AXISBANK.NS", "name": "Axis Bank"},
        {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank"},
        {"symbol": "SBIN.NS", "name": "State Bank of India"},
        {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank"},
    ],
    "Finance": [
        {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance"},
        {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv"},
        {"symbol": "SBICARD.NS", "name": "SBI Cards"},
        {"symbol": "CHOLAFIN.NS", "name": "Cholamandalam Investment"},
        {"symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance"},
        {"symbol": "MUTHOOTFIN.NS", "name": "Muthoot Finance"},
    ],
    "IT": [
        {"symbol": "TCS.NS", "name": "Tata Consultancy Services"},
        {"symbol": "INFY.NS", "name": "Infosys"},
        {"symbol": "WIPRO.NS", "name": "Wipro"},
        {"symbol": "HCLTECH.NS", "name": "HCL Technologies"},
        {"symbol": "TECHM.NS", "name": "Tech Mahindra"},
        {"symbol": "LTIM.NS", "name": "LTIMindtree"},
    ],
    "Healthcare": [
        {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical"},
        {"symbol": "DRREDDY.NS", "name": "Dr Reddy's Laboratories"},
        {"symbol": "CIPLA.NS", "name": "Cipla"},
        {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories"},
        {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals"},
        {"symbol": "LUPIN.NS", "name": "Lupin"},
    ],
    "Energy": [
        {"symbol": "RELIANCE.NS", "name": "Reliance Industries"},
        {"symbol": "ONGC.NS", "name": "Oil and Natural Gas Corporation"},
        {"symbol": "BPCL.NS", "name": "Bharat Petroleum"},
        {"symbol": "IOC.NS", "name": "Indian Oil Corporation"},
        {"symbol": "GAIL.NS", "name": "GAIL India"},
        {"symbol": "NTPC.NS", "name": "NTPC"},
    ],
    "FMCG": [
        {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever"},
        {"symbol": "ITC.NS", "name": "ITC"},
        {"symbol": "NESTLEIND.NS", "name": "Nestle India"},
        {"symbol": "DABUR.NS", "name": "Dabur India"},
        {"symbol": "BRITANNIA.NS", "name": "Britannia Industries"},
        {"symbol": "GODREJCP.NS", "name": "Godrej Consumer Products"},
    ],
    "Auto": [
        {"symbol": "MARUTI.NS", "name": "Maruti Suzuki"},
        {"symbol": "TATAMOTORS.NS", "name": "Tata Motors"},
        {"symbol": "M&M.NS", "name": "Mahindra and Mahindra"},
        {"symbol": "EICHERMOT.NS", "name": "Eicher Motors"},
        {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto"},
        {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp"},
    ],
    "Pharma": [
        {"symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma"},
        {"symbol": "GLENMARK.NS", "name": "Glenmark Pharmaceuticals"},
        {"symbol": "ALKEM.NS", "name": "Alkem Laboratories"},
        {"symbol": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals"},
        {"symbol": "BIOCON.NS", "name": "Biocon"},
        {"symbol": "ZYDUSLIFE.NS", "name": "Zydus Lifesciences"},
    ],
}
